config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'   
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :likes
  resources :sessions 
  resources :posts
  resources :followings 
  get '/index' => 'pages#index'
  get '/home' => 'pages#home'
  get '/profile' => 'pages#profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :followed_id, presence: true
  validates :follower_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }

  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one_attached :photo, dependent: :destroy
  has_one_attached :cover_image, dependent: :destroy

  has_many :passive_relationships, class_name: 'Following', foreign_key: 'followed_id', dependent: :destroy
  has_many :active_relationships, class_name: 'Following', foreign_key: 'follower_id', dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  default_scope -> { order(created_at: :desc) }

  validates_uniqueness_of :username
  validates :username, presence: true
  validates :full_name, presence: true

  # helper methods
  def follow(someone)
    active_relationships.create(follower_id: someone.id)
  end

  # unfollow methods
  def unfollow(someone)
    active_relationships.find_by(follower_id: someone.id).destroy
  end

  # is following a user
  def following?(someone)
    following.include?(someone)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def sign_in
    redirect_to root_path, notice: 'Please sign in first' unless current_user
  end

  def loged_in
    return if current_user
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    @following = current_user.active_relationships.build(followed_id: params[:id])
    @following.save
    redirect_to request.referrer
  end

  def destroy
    current_user.active_relationships.find_by(params[:id]).destroy
    redirect_to request.referrer
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(post_id: params[:post_id])

    if @like.save
      redirect_to request.referrer, notice: 'You just liked a tweet'
    else
      redirect_to request.referrer, alert: 'You can only like a tweet once.'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :sign_in, except: %i[index]

  def index; end

  def home
    @new_post = Post.new
    @posts = Post.order('created_at DESC').includes(:user, :likes).limit(10)
    @not_following = User.all - current_user.following
  end

  def profile
    @new_post = Post.new
    @user = User.find(params[:id].nil? ? current_user.id : params[:id])
    @followers = @user.followers
    @posts = @user.posts.includes(:user, :likes).limit(10)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :sign_in

  def index; end

  def new
    @posts = Posts.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |f|
      if @post.save
        f.html { redirect_to home_path, notice: 'Post Created' }
      else
        f.html { redirect_to home_path, notice: @post.errors.full_messages }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :sign_in, except: %i[new create]
  def index; end

  def show; end

  def new; end

  def create
    user = User.find_by(session_params)
    if user
      session[:user_id] = user.id
      redirect_to home_path, notice:
      "Welcome #{params[:username]}, successfully Signed In!"
    else
      redirect_to request.referrer, alert: 'Invalid Username'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'You signed out'
  end

  private

  def session_params
    params.require(:session).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to home_path, notice: 'Welcome Successfully Created Account.'
    else
      redirect_to request.referrer, alert: @user.errors.full_messages
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :full_name, :photo, :cover_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_signed_in
    if current_user
      render '/pages/navbar_layout'
    else
      render '/pages/welcome'
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def user_avatar(user_id)
    user = User.find(user_id)
    if user.photo.attached?
      image_tag user.photo, class: 'tweet_profile_mage'
    else
      image_tag 'default_avatar.jpg', class: 'tweet_profile_mage'
    end
  end

  def user_cover_image(user_id)
    user = User.find(user_id)
    if user.photo.attached?
      image_tag user.cover_image, class: 'cover_image'
    else
      image_tag 'default_cover_image.jpg', class: 'cover_image'
    end
  end

  def user_profile_image(user_id)
    user = User.find(user_id)
    if user.photo.attached?
      image_tag user.photo, class: 'profile_image_large'
    else
      image_tag 'default_avatar.jpg', class: 'profile_image_large'
    end
  end

  def not_followings(user)
    render '/pages/not_followings' if current_user.id != user.id
  end

  # rubocop:disable Style/GuardClause
  def follow_button(user)
    if current_user.id != user.id
      if !current_user.following?(user)
        link_to '+', followings_path(id: @user), method: :post, class: 'btn follow_button_add'
      else
        render 'components/follow_button'
      end
    end
  end

  def follow_follower_btn(follower)
    if current_user.id != follower.id
      if !current_user.following?(@follower)
        link_to '+', followings_path(id: @follower), method: :post, class: 'btn follow_button_add_sm'
      else
        render 'components/follow_follower_btn'
      end
    end
  end

  def unfollow_button(_user)
    if current_user.id != @user.id
      if !current_user.following?(@user)
        render 'components/unfollow_button'
      else
        link_to '-', following_path(id: @user.id), method: :delete, class: 'btn follow_button_sub'
      end
    end
  end
  # rubocop:enable Style/GuardClause
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterRedesignCapstone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/640b8b4dbe.js" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= user_signed_in %>  
  </body>
</html>

app/views/pages/_navbar_home.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">TWEETS <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">PHOTOS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">VEDEOS</a>
      </li>   
      
    </ul>
  </div>
</nav>

app/views/pages/_navbar_layout.html.erb
<div class="layout">
  <div class="left-side-nav">
    <div class="user_detail">
      <div class="row text-secondary">
        <div class="user_image_name d-flex pl-3 align-items-center">
          <%= user_avatar(current_user.id) %>   
          <span class="ml-2"><%= current_user.full_name %></span>          
        </div> 
      </div> 
      <div class="row text-secondary">
        <div class="user_following text-center">      
          <span class="large-font d-block"><%= current_user.following.count %></span> 
          <span>Following</span> 
        </div> 
        <div class="user_followers text-center">      
          <span class="large-font d-block"><%= current_user.followers.count %></span> 
          <span>Followers</span>
        </div> 
      </div>      
    </div>
    <div class="text-secondary">      
        <div class="side-nav d-flex align-items-center pl-3">
          <i class="fas fa-home"></i>
          <a class="nav-link nav-link-col" href="/home">HOME </a>
        </div>
        <div class="side-nav d-flex align-items-center pl-3">
          <i class="fas fa-user-circle"></i>
          <a class="nav-link nav-link-col" href="/profile">PROFILE</a>
        </div>
        <div class="side-nav d-flex align-items-center pl-3">
          <i class="fas fa-power-off"></i>
          <%= link_to 'LOG OUT', session_path('active'), method: :delete, class: 'nav-link-col side-nav-last' %>        
        </div> 
    </div>
  </div>
  <div class="right-side-nav"> 
    <div>
      <%= render '/pages/top_navbar' %>
    </div>
    <div class="home_container">
      <%= yield %>      
    </div>
  </div>
</div>

app/views/pages/_navbar_user.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">TWEETS <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">PHOTOS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">FOLLOWING</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">FOLLOWING</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">FAVORITES</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">LISTS</a>
      </li>
      
    </ul>
  </div>
</nav>

app/views/pages/_not_followings.html.erb
 <%= user_avatar(@user_not_followed.id) %>   
 <span class="ml-2"><%= link_to @user_not_followed.full_name, profile_path(id: @user_not_followed.id), class: 'text-secondary' %></span> 
             

app/views/pages/_top_navbar.html.erb
<div class="top-navbar d-flex justify-content-between">
  <div class="top-logo">
    <i class="fab fa-twitter"></i>
  </div>
  <div class="social-links">
    <i class="fas fa-pen"></i>
    <i class="fas fa-envelope"></i>
    <i class="fas fa-search"></i>
    <i class="fas fa-cog"></i>
  </div>
</div>

app/views/pages/_welcome.html.erb
  <div class="container-index row">
    <div class="col-7">  
      <h1 class="text"> Welcome to Twitter </h1>
        <p class="text">
        Hi welcome to twitter. It seems like there’s not a lot to show</br> 
         you right now, Lorem ipsum dolor sit amet, consectetur adipiscing </br>
         elit. Integer posuere erat a ante.Someone famous  </br> 
        </p>
        <h3 class='text'>             
          <%= link_to 'Sign In', new_session_path, class: 'text' %> |
          <%= link_to 'Sign Up', new_user_path, class: 'text' %>
        </h3>
        
        
    </div>

    <div class="container col-5">     
      

      <%= yield %>
      </div>       

    </div>

app/views/pages/home.html.erb
    <div class="home-middle-content">
        <div class="midle-nav">
            <%= render 'navbar_home' %>
        </div>
        <div class="ml-5">
            <span class="notice"><%= notice %></span>
            <span class="alert"><%= alert %></span>
        </div>
        <div class="container">
        <div class="card  card-post mb-2">
        <div class="card-body">
        <%= form_for(@new_post) do |f| %>
            <p class="text-secondary">TWEET SOMETHING</p> 
            <div class="input-group mb-1"> 
            <%= f.text_field :content, autofocus: true, class: "form-control" %>
            <%= f.submit "Add Tweet" %>                 
            </div>
            <% end %>
        </div>
        </div>
            <p>
            <% for p in @posts do %>
                <div class="card card-post">
                    <div class="card-body d-flex">
                        <div class="tweet_avatar mr-3"> 
                            <%= user_avatar(p.user_id) %>                                         
                        </div> 
                        <div class="tweet_content">
                            <div  class="d-flex justify-content-between">                             
                                <p><%= link_to p.user.full_name, profile_path(id: p.user_id), class: 'text-dark' %></p>
                                <p class="text-secondary"><%= p.created_at.to_formatted_s(:short) %></p>
                            </div> 
                            <p class="text-secondary"><%= p.content %></p>
                            <div class="d-flex justify-content-end align-items-center"> 
                                <span class="mr-2"> <%=  p.likes.count %> </span>
                                <%= link_to '', likes_path(post_id: p.id), method: :post, class: 'fas fa-heart like_btn text-secondary' %> 
                            </div>                       
                        </div>                     
                    </div>    
                </div>
            <% end %>      
            </p>
        </div>
    </div>

    <div class="home-right-content">
      <div class="text-secondary pt-3 who-to-follow d-flex">
        <p class="mr-5"> WHO TO FOLLOW </p> <i class="fas fa-sync ml-4 mt-1 text-secondary"></i>
      </div> 
        <div>       
        <% for @user_not_followed in @not_following do %>
            <div class="user_image_name d-flex pl-3 align-items-center">
              <%= not_followings(@user_not_followed) %> 
            </div>             
          <% end %>
        </div> 
    </div>
    

app/views/pages/profile.html.erb
<div class="home-middle-content">
    <div class="banner">
      <%= user_cover_image(@user.id) %>   
    </div>
    <div class="midle-nav">
    <%= render 'navbar_user' %>        
    </div>
    <div class="ml-5">
      <span class="notice"><%= notice %></span>
      <span class="alert"><%= alert %></span>
    </div>
    <div class="container">
    <div class="card  card-post mb-2">
      <div class="card-body">
      <%= form_for(@new_post) do |f| %>
        <p class="text-secondary">TWEET SOMETHING</p> 
        <div class="input-group mb-1"> 
          <%= f.text_field :content, autofocus: true, class: "form-control" %>
          <%= f.submit "Add Tweet" %>                 
        </div>
        <% end %>
      </div>
    </div>
    <p>
    <% for p in @posts do %>
      <div class="card card-post">
          <div class="card-body d-flex">
              <div class="tweet_avatar mr-3"> 
                  <%= user_avatar(p.user_id) %>                                                           
              </div> 
              <div class="tweet_content">
                  <div  class="d-flex justify-content-between"> 
                      <p><%= User.find(p.user_id).full_name %></p>
                      <p class="text-secondary"><%= p.created_at.to_formatted_s(:short) %></p>
                  </div> 
                  <p class="text-secondary"><%= p.content %></p>
                  <div class="d-flex justify-content-end align-items-center"> 
                    <span class="mr-2"> <%=  p.likes.count %> </span>
                    <%= link_to '', likes_path(post_id: p.id), method: :post, class: 'fas fa-heart like_btn text-secondary' %> 
                  </div>                     
              </div>                     
          </div>    
      </div>
  <% end %>       
    </p>
    </div> 
</div>

<div class="home-right-content">
  <div class="profile_large_image_name">
    <div class="profile_large_image d-flex flex-column align-items-center justify-content-center">
        <div class="d-flex align-items-center">
          <div class="round_follow_btn mr-2">
              <%= follow_button(@user) %>
          </div>
          <div>
              <%= user_profile_image(@user.id) %>                          
          </div> 
          <div class="round_follow_btn ">
              <%= unfollow_button(@user) %>
          </div>
        </div>
      </div>
    </div>
    <div>
      <p class="mt-3 d-flex justify-content-center"><%= @user.full_name.upcase %>  </p>
    <div>
    <div class="profile_numbers d-flex">
          <div class="profile_numbers_item text-center flex-fill text-secondary">      
            <span class="large-font d-block text-dark"><%= @user.posts.count %></span> 
            <span>Tweets</span> 
          </div> 
          <div class="profile_numbers_item text-center flex-fill text-secondary">      
            <span class="large-font d-block text-dark"><%= @user.following.count %></span> 
            <span>Following</span>
          </div>
          <div class="profile_numbers_item text-center flex-fill text-secondary">      
            <span class="large-font d-block text-dark"><%= @user.followers.count %></span> 
            <span>Followers</span> 
          </div> 
    </div> 
  

  <div class="followed_by d-flex text-secondary d-flex p-3 ">
      <p> FOLLOWED BY </p>
  </div>
  </div> 
  <div class="d-block">       
        <% for @follower in @followers do %>
            <div class="user_image_name d-flex pl-3 align-items-center justify-content-between">
                <div>
                  <%= user_avatar(@follower.id) %>  
                  <%= link_to @follower.full_name, profile_path(id: @follower.id), class: 'text-secondary' %> 
                </div>
                <div class="follower_follow">
                  <%= follow_follower_btn(@follower) %> 
                </div>    
            </div>             
        <% end %>
  </div>    
  
</div>


    

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/users/index.html.erb
<h1> views/users/index </h1>

app/views/users/new.html.erb
<div class="signup_form text" >
<h1 class="text"> Create Account </h1>
<%= form_for @user do |f| %>
  
  <div class="field text">
    <%= f.label :username %><br/>
    <%= f.text_field :username, autofocus: true, autocomplete: "User name" %>
  </div>
  <div class="field text">
    <%= f.label :full_name %><br/>
    <%= f.text_field :full_name, autocomplete: "Full name" %>
  </div>  
  <div class="text">
    <%= f.label :Profile_Image %><br/>
    <%= f.file_field :photo %>
  </div> 
  <div class="text">
    <%= f.label :Cover_Image %><br/>
    <%= f.file_field :cover_image %>    
  </div> 

  <div class="actions">
  <br/>
    <%= f.submit "Sign up" %>
  </div>
<% end %>
<div class="mt-2 text-danger">
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span>
</div>
</div>